language: generic
services:
  - docker
env:
  matrix:
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="melodic"

matrix:
  allow_failures:
- env: ROS_DISTRO="melodic" #getting ready to support melodic

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh